services:
  postgres:
    image: postgres:18.1-alpine3.23
    container_name: toroid-postgres
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    ports:
      - "5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
  redis:
    image: redis:8.4.0-alpine
    container_name: toroid-redis
    ports:
      - "6379"
    volumes:
      - redis-data:/data
  open-telemetry:
    image: grafana/otel-lgtm
    ports:
      - "3000:3000"
      - "4317"
      - "4318"
volumes:
  postgres-data:
  redis-data:
